# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: control main branch

on:
  push:
  pull_request: 
    branches: 
      - main

jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Je vérifie que le code compile bien"
